//******************************************************************************
//* clean.js
//*
//* Defines a custom gulp task for removing all output files that were 
//* autogenerated by other custom gulp tasks 
//******************************************************************************

"use strict";

//******************************************************************************
//* DEPENDENCIES
//******************************************************************************

var gulp = require("gulp"),
    clean = require('gulp-clean');

//******************************************************************************
//* CLEAN
//******************************************************************************

gulp.task('clean', function() {
    var directories = [];
    directories.push(global.TSCompiledOutput.RootFolder);
    directories.push(global.TSCompiledOutput.TestRootFolder);
    directories.push(global.TSDist.RootFolder);
    directories.push(global.TSDist.SrcFolder);
    directories.push(global.PnPLocalServer.RootFolder + "/" + global.PnPLocalServer.ScriptsRootFolder);

    return gulp.src(directories, { read: false })
        .pipe(clean());
});